An update.

diff --git a/make-rpm b/make-rpm
--- a/make-rpm
+++ b/make-rpm
@@ -150,6 +150,13 @@ for DISTRIBUTION in $DISTRIBUTIONS ; do
    echo -e "\x1b[34m`date +%FT%H:%M:%S`: ====== Creating binary RPM for $DISTRIBUTION ==========\x1b[0m"
    echo -e ""
 
+   if [ ! -e "/etc/mock/$DISTRIBUTION.cfg" ] ; then
+      echo >&2 "ERROR: Cannot find /etc/mock/$DISTRIBUTION.cfg!"
+      exit 1
+   fi
+   # NOTE: DISTRIBUTION may point to another directory (e.g. "rawhide" instead of "30")!
+   distribution=`grep "config_opts..root.. =" /etc/mock/$DISTRIBUTION.cfg | sed -e "s/^.* = //g" -e "s/'//g"`
+
    # Remove old files
    find /var/lib/mock/$DISTRIBUTION/result -name "$PACKAGE-*.rpm" | xargs --no-run-if-empty rm -f
 
@@ -161,7 +168,7 @@ for DISTRIBUTION in $DISTRIBUTIONS ; do
    mock -r $DISTRIBUTION --old-chroot --no-clean --rebuild $PACKAGE_SRPM
 
    # Check whether files are at the right location
-   PACKAGE_RPMS=`find /var/lib/mock/$DISTRIBUTION/result -name "$PACKAGE-*$PACKAGE_VERSION*-*.rpm" | grep -v "$PACKAGE-*$PACKAGE_VERSION*-*.src.rpm" || true`
+   PACKAGE_RPMS=`find /var/lib/mock/$distribution/result -name "$PACKAGE-*$PACKAGE_VERSION*-*.rpm" | grep -v "$PACKAGE-*$PACKAGE_VERSION*-*.src.rpm" || true`
    if [ "$PACKAGE_RPMS" == "" ] ; then
       echo >&2 "ERROR: Cannot find RPMs!"
       exit 1
