Improved script.

diff --git a/make-ppa b/make-ppa
--- a/make-ppa
+++ b/make-ppa
@@ -41,6 +41,10 @@ done
 ./clean-deb
 if [ ${DPUT} -ne 0 ] ; then
    . ./debian.conf
+   if [ "${NOT_TARGET_DISTRIBUTIONS}" == "" ] ; then
+      echo >&2 "ERROR: Define NOT_TARGET_DISTRIBUTIONS in debian.conf!"
+      exit 1
+   fi
    buildForDistribution=""
    for dputDistribution in ${DPUT_DISTRIBUTIONS} ; do
       notATarget=0
@@ -54,11 +58,11 @@ if [ ${DPUT} -ne 0 ] ; then
          buildForDistribution="${buildForDistribution} ${dputDistribution}"
       fi
    done
-   echo "Building for distributions: ${buildForDistribution}"
-exit 1
 
+   echo "Building for distributions:${buildForDistribution}"
    ./make-deb ${buildForDistribution}
 fi
+
 if [ ${COPR} -ne 0 ] ; then
    if [ -e rpm -o -e ./make-srpm ] ; then
       ./make-srpm || exit 1
