Another try.

diff --git a/ci/build b/ci/build
--- a/ci/build
+++ b/ci/build
@@ -69,6 +69,7 @@ if [ "${TRAVIS_OS_NAME}" == "linux" ] ; then
    # ====== Travis CI standard Ubuntu Linux machine =========================
    # That is: not using Docker
    else
+      # ====== Configure ====================================================
       if [ -e CMakeLists.txt ] ; then
          env CC=${COMPILER_C} CXX=${COMPILER_CXX} cmake . $@
       elif [ -e configure.ac -o -e configure.in ] ; then
@@ -84,11 +85,22 @@ if [ "${TRAVIS_OS_NAME}" == "linux" ] ; then
          echo >&2 "WARNING: No build system detected. Trying to just call \"make\" ..."
       fi
 
-      cores=`getconf _NPROCESSORS_ONLN 2>/dev/null || true`
-      if [ $cores -gt 1 ] ; then
-         MAKEFLAGS="-j${cores}"
+      # ====== Compile ======================================================
+      if [ "${TOOL}" == "compile" ] ; then
+         cores=`getconf _NPROCESSORS_ONLN 2>/dev/null || true`
+         if [ $cores -gt 1 ] ; then
+            MAKEFLAGS="-j${cores}"
+         fi
+         env MAKEFLAGS=${MAKEFLAGS} make   # VERBOSE=1
+
+      # ====== Coverity Scan ================================================
+      elif [ "${TOOL}" == "coverity" ] ; then
+         echo "Skipping build for Coverity Scan."
+
+      else
+         echo >&2 "ERROR: Invalid setting of TOOL=${TOOL}"
+         exit 1
       fi
-      env MAKEFLAGS=${MAKEFLAGS} make   # VERBOSE=1
    fi
 
 
