Improved scripts.

diff --git a/ci/build b/ci/build
--- a/ci/build
+++ b/ci/build
@@ -22,55 +22,8 @@
 . `dirname $0`/get-container
 
 
-# ###### Linux via Docker ###################################################
-if [ "${TRAVIS_OS_NAME}" == "linux" -a "${DOCKER}" != "" -a "${QEMU}" == "" ] ; then
-
-   # ====== Compile (generic) ===============================================
-   if [ "${TOOL}" == "compile" ] ; then
-      echo "###### Compiling ... ##################################################"
-
-      if [ -e CMakeLists.txt ] ; then
-         sudo docker exec ${CONTAINER} env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} cmake . $@
-      elif [ -e configure.ac -o -e configure.in ] ; then
-         if [ -e bootstrap ] ; then
-            sudo docker exec ${CONTAINER} env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./bootstrap
-            sudo docker exec ${CONTAINER} env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./configure $@
-         elif [ -e autogen.sh ] ; then
-            sudo docker exec ${CONTAINER} env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./autogen.sh
-         else
-            sudo docker exec ${CONTAINER} env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./configure $@
-         fi
-      else
-         echo >&2 "WARNING: No build system detected. Trying to just call \"make\" ..."
-      fi
-
-      cores=`sudo docker exec ${CONTAINER} env LANG=C.UTF-8 getconf _NPROCESSORS_ONLN 2>/dev/null || true`
-      if [ $cores -gt 1 ] ; then
-         MAKEFLAGS="-j${cores}"
-      fi
-      sudo docker exec ${CONTAINER} env LANG=C.UTF-8 MAKEFLAGS=${MAKEFLAGS} make   # VERBOSE=1
-
-   # ====== PBuilder (Debian/Ubuntu variants) ===============================
-   elif [ "${TOOL}" == "pbuilder" ] ; then
-      echo "###### Running pbuilder ... ###########################################"
-      sudo docker exec ${CONTAINER} env LANG=C.UTF-8 OVERRIDE_SKIP_PACKAGE_SIGNING=1 eatmydata ./build-deb
-
-   # ====== Mock (Fedora variants) ==========================================
-   elif [ "${TOOL}" == "mock" ] ; then
-      echo "###### Running mock ... ###############################################"
-      release=`sudo docker exec -t ${CONTAINER} bash -c "LANG=C.UTF-8 ; cat /etc/fedora-release | sed -e \"s/^\(.*\) release \([0-9]*\) (\(.*\))$/\2/g\"" | sed -e "s/[^0-9]//g"`
-      arch=`sudo docker exec -t ${CONTAINER} env LANG=C.UTF-8 uname -m | sed -e "s/[^0-9a-zA-Z_+-]//g"`
-      sudo docker exec ${CONTAINER} env LANG=C.UTF-8 LD_PRELOAD=/usr/lib64/nosync/nosync.so OVERRIDE_SKIP_PACKAGE_SIGNING=1 ./build-rpm fedora-${release}-${arch}
-
-   # ====== Invalid setting =================================================
-   else
-      echo >&2 "ERROR: Invalid setting of TOOL=${TOOL}!"
-      exit 1
-   fi
-
-
 # ###### Linux as-is ########################################################
-elif [ "${TRAVIS_OS_NAME}" == "linux" -a "${DOCKER}" == "" -a "${QEMU}" == "" ] ; then
+if [ "${TRAVIS_OS_NAME}" == "linux" -a "${DOCKER}" == "" -a "${QEMU}" == "" ] ; then
    # ====== Configure with CMake ============================================
    if [ -e CMakeLists.txt ] ; then
       env CC=${COMPILER_C} CXX=${COMPILER_CXX} cmake . $@
@@ -133,7 +86,7 @@ elif [ "${TRAVIS_OS_NAME}" == "linux" -a "${DOCKER}" == "" -a "${QEMU}" == "" ] 
    fi
 
 
-# ###### FreeBSD ############################################################
+# ###### FreeBSD via QEMU ###################################################
 elif [ "${TRAVIS_OS_NAME}" == "linux" -a "${QEMU}" == "FreeBSD" ] ; then
 
    ssh -p 8829 -i ~/.ssh/id_rsa root@localhost <<EOF
@@ -165,6 +118,53 @@ elif [ "${TRAVIS_OS_NAME}" == "linux" -a "${QEMU}" == "FreeBSD" ] ; then
       echo "Done!"
       exit 0
 EOF
+
+
+# ###### Linux via Docker ###################################################
+elif [ "${TRAVIS_OS_NAME}" == "linux" -a "${DOCKER}" != "" -a "${QEMU}" == "" ] ; then
+
+   # ====== Compile (generic) ===============================================
+   if [ "${TOOL}" == "compile" ] ; then
+      echo "###### Compiling ... ##################################################"
+
+      if [ -e CMakeLists.txt ] ; then
+         sudo docker exec ${CONTAINER} env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} cmake . $@
+      elif [ -e configure.ac -o -e configure.in ] ; then
+         if [ -e bootstrap ] ; then
+            sudo docker exec ${CONTAINER} env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./bootstrap
+            sudo docker exec ${CONTAINER} env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./configure $@
+         elif [ -e autogen.sh ] ; then
+            sudo docker exec ${CONTAINER} env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./autogen.sh
+         else
+            sudo docker exec ${CONTAINER} env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./configure $@
+         fi
+      else
+         echo >&2 "WARNING: No build system detected. Trying to just call \"make\" ..."
+      fi
+
+      cores=`sudo docker exec ${CONTAINER} env LANG=C.UTF-8 getconf _NPROCESSORS_ONLN 2>/dev/null || true`
+      if [ $cores -gt 1 ] ; then
+         MAKEFLAGS="-j${cores}"
+      fi
+      sudo docker exec ${CONTAINER} env LANG=C.UTF-8 MAKEFLAGS=${MAKEFLAGS} make   # VERBOSE=1
+
+   # ====== pbuilder (Debian/Ubuntu variants) ===============================
+   elif [ "${TOOL}" == "pbuilder" ] ; then
+      echo "###### Running pbuilder ... ###########################################"
+      sudo docker exec ${CONTAINER} env LANG=C.UTF-8 OVERRIDE_SKIP_PACKAGE_SIGNING=1 eatmydata ./build-deb
+
+   # ====== mock (Fedora variants) ==========================================
+   elif [ "${TOOL}" == "mock" ] ; then
+      echo "###### Running mock ... ###############################################"
+      release=`sudo docker exec -t ${CONTAINER} bash -c "LANG=C.UTF-8 ; cat /etc/fedora-release | sed -e \"s/^\(.*\) release \([0-9]*\) (\(.*\))$/\2/g\"" | sed -e "s/[^0-9]//g"`
+      arch=`sudo docker exec -t ${CONTAINER} env LANG=C.UTF-8 uname -m | sed -e "s/[^0-9a-zA-Z_+-]//g"`
+      sudo docker exec ${CONTAINER} env LANG=C.UTF-8 LD_PRELOAD=/usr/lib64/nosync/nosync.so OVERRIDE_SKIP_PACKAGE_SIGNING=1 ./build-rpm fedora-${release}-${arch}
+
+   # ====== Invalid setting =================================================
+   else
+      echo >&2 "ERROR: Invalid setting of TOOL=${TOOL}!"
+      exit 1
+   fi
 
 
 # ###### MacOS X ############################################################
