Another try.

diff --git a/ci/build b/ci/build
--- a/ci/build
+++ b/ci/build
@@ -21,44 +21,74 @@
 
 # ###### Linux ##############################################################
 if [ "${TRAVIS_OS_NAME}" == "linux" ] ; then
-   if [ "${TOOL}" == "compile" ] ; then
-      echo "###### Compiling ... ##################################################"
 
+   # ====== Docker ==========================================================
+   if [ "${DOCKER}" != "" ] ; then
+
+      if [ "${TOOL}" == "compile" ] ; then
+         echo "###### Compiling ... ##################################################"
+
+         if [ -e CMakeLists.txt ] ; then
+            sudo docker exec ubuntu-test env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} cmake . $@
+         elif [ -e configure.ac -o -e configure.in ] ; then
+            if [ -e bootstrap ] ; then
+               sudo docker exec ubuntu-test env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./bootstrap
+               sudo docker exec ubuntu-test env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./configure $@
+            elif [ -e autogen.sh ] ; then
+               sudo docker exec ubuntu-test env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./autogen.sh
+            else
+               sudo docker exec ubuntu-test env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./configure $@
+            fi
+         else
+            echo >&2 "WARNING: No build system detected. Trying to just call \"make\" ..."
+         fi
+
+         cores=`sudo docker exec ubuntu-test env LANG=C.UTF-8 getconf _NPROCESSORS_ONLN 2>/dev/null || true`
+         if [ $cores -gt 1 ] ; then
+            MAKEFLAGS="-j${cores}"
+         fi
+         sudo docker exec ubuntu-test env LANG=C.UTF-8 MAKEFLAGS=${MAKEFLAGS} make   # VERBOSE=1
+
+      elif [ "${TOOL}" == "pbuilder" ] ; then
+         echo "###### Running pbuilder ... ###########################################"
+         sudo docker exec ubuntu-test env LANG=C.UTF-8 sed -e 's/SKIP_PACKAGE_SIGNING=0/SKIP_PACKAGE_SIGNING=1/g' -i debian.conf
+         sudo docker exec ubuntu-test env LANG=C.UTF-8 eatmydata ./build-deb
+
+      elif [ "${TOOL}" == "mock" ] ; then
+         echo "###### Running mock ... ###############################################"
+         release=`sudo docker exec -t ubuntu-test bash -c "LANG=C.UTF-8 ; cat /etc/fedora-release | sed -e \"s/^\(.*\) release \([0-9]*\) (\(.*\))$/\2/g\"" | sed -e "s/[^0-9]//g"`
+         arch=`sudo docker exec -t ubuntu-test env LANG=C.UTF-8 uname -m | sed -e "s/[^0-9a-zA-Z_-+]//g"`
+         sudo docker exec ubuntu-test env LANG=C.UTF-8  ./build-rpm fedora-${release}-${arch}
+
+      else
+         echo >&2 "ERROR: Invalid setting of TOOL=${TOOL}"
+         exit 1
+      fi
+
+
+   # ====== Travis CI standard Ubuntu Linux machine =========================
+   # That is: not using Docker
+   else
       if [ -e CMakeLists.txt ] ; then
-         sudo docker exec ubuntu-test env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} cmake . $@
+         env CC=${COMPILER_C} CXX=${COMPILER_CXX} cmake . $@
       elif [ -e configure.ac -o -e configure.in ] ; then
          if [ -e bootstrap ] ; then
-            sudo docker exec ubuntu-test env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./bootstrap
-            sudo docker exec ubuntu-test env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./configure $@
+            env CC=${COMPILER_C} CXX=${COMPILER_CXX} ./bootstrap
+            env CC=${COMPILER_C} CXX=${COMPILER_CXX} ./configure $@
          elif [ -e autogen.sh ] ; then
-            sudo docker exec ubuntu-test env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./autogen.sh
+            env CC=${COMPILER_C} CXX=${COMPILER_CXX} ./autogen.sh
          else
-            sudo docker exec ubuntu-test env LANG=C.UTF CC=${COMPILER_C} CXX=${COMPILER_CXX} ./configure $@
+            env CC=${COMPILER_C} CXX=${COMPILER_CXX} ./configure $@
          fi
       else
          echo >&2 "WARNING: No build system detected. Trying to just call \"make\" ..."
       fi
 
-      cores=`sudo docker exec ubuntu-test env LANG=C.UTF-8 getconf _NPROCESSORS_ONLN 2>/dev/null || true`
+      cores=`getconf _NPROCESSORS_ONLN 2>/dev/null || true`
       if [ $cores -gt 1 ] ; then
          MAKEFLAGS="-j${cores}"
       fi
-      sudo docker exec ubuntu-test env LANG=C.UTF-8 MAKEFLAGS=${MAKEFLAGS} make   # VERBOSE=1
-
-   elif [ "${TOOL}" == "pbuilder" ] ; then
-      echo "###### Running pbuilder ... ###########################################"
-      sudo docker exec ubuntu-test env LANG=C.UTF-8 sed -e 's/SKIP_PACKAGE_SIGNING=0/SKIP_PACKAGE_SIGNING=1/g' -i debian.conf
-      sudo docker exec ubuntu-test env LANG=C.UTF-8 eatmydata ./build-deb
-
-   elif [ "${TOOL}" == "mock" ] ; then
-      echo "###### Running mock ... ###############################################"
-      release=`sudo docker exec -t ubuntu-test bash -c "LANG=C.UTF-8 ; cat /etc/fedora-release | sed -e \"s/^\(.*\) release \([0-9]*\) (\(.*\))$/\2/g\"" | sed -e "s/[^0-9]//g"`
-      arch=`sudo docker exec -t ubuntu-test env LANG=C.UTF-8 uname -m | sed -e "s/[^0-9a-zA-Z_-+]//g"`
-      sudo docker exec ubuntu-test env LANG=C.UTF-8  ./build-rpm fedora-${release}-${arch}
-
-   else
-      echo >&2 "ERROR: Invalid setting of TOOL=${TOOL}"
-      exit 1
+      env MAKEFLAGS=${MAKEFLAGS} make   # VERBOSE=1
    fi
 
 
