Another try.

diff --git a/ci/build b/ci/build
--- a/ci/build
+++ b/ci/build
@@ -84,18 +84,35 @@ if [ "${TRAVIS_OS_NAME}" == "linux" ] ; then
       else
          echo >&2 "WARNING: No build system detected. Trying to just call \"make\" ..."
       fi
+      cores=`getconf _NPROCESSORS_ONLN 2>/dev/null || true`
+      if [ $cores -gt 1 ] ; then
+         MAKEFLAGS="-j${cores}"
+      fi
 
       # ====== Compile ======================================================
       if [ "${TOOL}" == "compile" ] ; then
-         cores=`getconf _NPROCESSORS_ONLN 2>/dev/null || true`
-         if [ $cores -gt 1 ] ; then
-            MAKEFLAGS="-j${cores}"
-         fi
          env MAKEFLAGS=${MAKEFLAGS} make   # VERBOSE=1
 
       # ====== Coverity Scan ================================================
       elif [ "${TOOL}" == "coverity" ] ; then
-         echo "Skipping build for Coverity Scan."
+         # ------ Build -----------------------------------------------------
+         env MAKEFLAGS=${MAKEFLAGS} cov-build --dir cov-int make
+         tar czf coverity-results.tar.gz cov-int
+         ls -l coverity-results.tar.gz
+
+         # ------ Upload results --------------------------------------------
+         curl --form token=${COVERITY_SCAN_TOKEN} \
+           --form email=${COVERITY_EMAIL} \
+           --form file=@coverity-results.tar.gz \
+           --form version="master branch head" \
+           --form description="$(git log -1|head -1)" \
+           https://scan.coverity.com/builds?project=${COVERITY_PROJECT}
+         CURL_RESULT=$?
+         echo "curl returned ${CURL_RESULT}"
+         if [ $CURL_RESULT -ne 0 ]; then
+            echo >&2 "ERROR: Upload to Coverity Scan failed; curl returned ${CURL_RESULT}!"
+            exit 1
+         fi
 
       else
          echo >&2 "ERROR: Invalid setting of TOOL=${TOOL}"
