Improved CI scripts.

diff --git a/ci/ci-setup b/ci/ci-setup
--- a/ci/ci-setup
+++ b/ci/ci-setup
@@ -19,11 +19,11 @@
 # Contact: thomas.dreibholz@gmail.com
 
 # Bash options:
-set -e
+set -eu
 
-UNAME=`uname`
+
+# ====== Check arguments ====================================================
 USE_PACKAGING=0
-
 while [ $# -gt 0 ] ; do
    if [ "$1" == "package" ] ; then
       USE_PACKAGING=1
@@ -31,20 +31,30 @@ while [ $# -gt 0 ] ; do
    shift
 done
 
+# ====== Check/set environment variables ====================================
+UNAME="$(uname)"
+if [ ! -e /etc/os-release ] ; then
+   echo >&2 "ERROR: /etc/os-release does not exist!"
+   exit 1
+fi
+. /etc/os-release
 
-# ###### Linux ##############################################################
+
+# ====== Linux ==============================================================
 if [ "${UNAME}" == "Linux" ] ; then
 
    # NOTE: lsb_release may not be installed, yet!
    # => Guess distribution by checking for the packaging tool.
 
    # ====== Ubuntu/Deban ====================================================
-   if [ -e /usr/bin/apt-get ] ; then
+   if [ "${ID}" == "ubuntu" ] || [ "${ID}" == "debian" ] ; then
       PACKAGES="lsb-release python3"
-      if [[ "${CC}" =~ .*gcc.* ]] ; then
-          PACKAGES="${PACKAGES} gcc"
-      elif [[ "${CC}" =~ .*clang.* ]] ; then
-          PACKAGES="${PACKAGES} clang"
+      if [ -v CC ] ; then
+         if [[ "${CC}" =~ .*gcc.* ]] ; then
+            PACKAGES="${PACKAGES} gcc"
+         elif [[ "${CC}" =~ .*clang.* ]] ; then
+            PACKAGES="${PACKAGES} clang"
+         fi
       fi
       if [ ${USE_PACKAGING} -eq 1 ] ; then
          # Need to install pbuilder as well:
@@ -53,10 +63,11 @@ if [ "${UNAME}" == "Linux" ] ; then
 
       apt-get update -qq
       # DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -qy
+      # shellcheck disable=SC2086
       DEBIAN_FRONTEND=noninteractive apt-get install -qqy  -o Dpkg::Options::=--force-confold -o Dpkg::Options::=--force-confdef --no-install-recommends \
          ${PACKAGES}
 
-      if [ "`lsb_release -is`" == "Ubuntu" ] ; then
+      if [ "${ID}" == "ubuntu" ] ; then
          # Add PPA dreibh/ppa for Ubuntu:
          DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::=--force-confold -o Dpkg::Options::=--force-confdef --no-install-recommends \
             software-properties-common
@@ -70,14 +81,14 @@ if [ "${UNAME}" == "Linux" ] ; then
          # https://github.com/jrl-umi3218/github-actions/tree/master/setup-pbuilder
 
          if [ "${OS}" == "" ] ; then
-            OS=`lsb_release -is`
+            OS=$(lsb_release -is)
             OS=${OS,,}
          fi
          if [ "${DIST}" == "" ] ; then
-            DIST=`lsb_release -cs`
+            DIST=$(lsb_release -cs)
          fi
          if [ "${ARCH}" == "" ] ; then
-            ARCH=`dpkg --print-architecture`
+            ARCH=$(dpkg --print-architecture)
          fi
 
          if [ "${OS}" == "ubuntu" ] ; then
@@ -86,7 +97,7 @@ if [ "${UNAME}" == "Linux" ] ; then
             KEYRING="/usr/share/keyrings/ubuntu-archive-keyring.gpg"
          elif [ "${OS}" == "debian" ] ; then
             COMPONENTS="main"
-            if [ "${ARCH}" == "m68k" -o  "${ARCH}" == "riscv64" ] ; then
+            if [ "${ARCH}" == "m68k" ] || [ "${ARCH}" == "riscv64" ] ; then
                # Debian Ports (special architectures)
                MIRRORSITE="http://ftp.ports.debian.org/debian-ports/"
                KEYRING="/usr/share/keyrings/debian-ports-archive-keyring.gpg"
@@ -100,7 +111,7 @@ if [ "${UNAME}" == "Linux" ] ; then
             exit 1
          fi
 
-         cores=`getconf _NPROCESSORS_ONLN 2>/dev/null || true`
+         cores=$(getconf _NPROCESSORS_ONLN 2>/dev/null || true)
          cat >/etc/pbuilderrc <<EOF
 #!/bin/bash -e
 
@@ -163,7 +174,7 @@ EOF
 
 
    # ====== Fedora ==========================================================
-   elif [ -e /usr/bin/dnf ] ; then
+   elif [ "${ID}" == "fedora" ] ; then
       PACKAGES="clang make python3 redhat-lsb-core"
       if [ ${USE_PACKAGING} -eq 1 ] ; then
          # Need to install mock as well:
@@ -171,21 +182,21 @@ EOF
       fi
 
       # dnf upgrade -qy
+      # shellcheck disable=SC2086
       dnf install -qy ${PACKAGES}
 
       if [ ${USE_PACKAGING} -eq 1 ] ; then
-         # ====== mock environment ==========================================
+         # ====== Mock environment ==========================================
          groupadd -f mock
 
-         release=`cat /etc/fedora-release | sed -e "s/^\(.*\) release \([0-9]*\) (\(.*\))$/\2/g" | sed -e  "s/[^0-9]//g"`
-         arch=`uname -m | sed -e "s/[^0-9a-zA-Z_+-]//g"`
-         if ! grep "^\[copr-dreibh-ppa\]" /etc/mock/fedora-${release}-${arch}.cfg ; then
+         arch=$(uname -m | sed -e "s/[^0-9a-zA-Z_+-]//g")
+         if ! grep "^\[copr-dreibh-ppa\]" /etc/mock/fedora-"${VERSION_ID}"-"${arch}".cfg ; then
             shopt -s extglob
             ppa="config_opts['dnf.conf'] += \"\"\"\n[copr-dreibh-ppa]\nname=Copr repo for ppa owned by dreibh\nbaseurl=https://copr-be.cloud.fedoraproject.org/results/dreibh/ppa/fedora-\$releasever-\$basearch/\ntype=rpm-md\nskip_if_unavailable=True\ngpgcheck=1\ngpgkey=https://copr-be.cloud.fedoraproject.org/results/dreibh/ppa/pubkey.gpg\nrepo_gpgcheck=0\nenabled=1\n\"\"\""
             ppa="${ppa//+( )$/\\n}"
-            echo -e "${ppa}" | tee -a /etc/mock/fedora-${release}-${arch}.cfg
-            if ! grep "^\[copr-dreibh-ppa\]" /etc/mock/fedora-${release}-${arch}.cfg ; then
-               echo >&2 "ERROR: Unable to inject PPA configuration into Mock configuration file /etc/mock/fedora-${release}-${arch}.cfg!"
+            echo -e "${ppa}" | tee -a /etc/mock/fedora-"${VERSION_ID}"-"${arch}".cfg
+            if ! grep "^\[copr-dreibh-ppa\]" /etc/mock/fedora-"${VERSION_ID}"-"${arch}".cfg ; then
+               echo >&2 "ERROR: Unable to inject PPA configuration into Mock configuration file /etc/mock/fedora-${VERSION_ID}-${arch}.cfg!"
                exit 1
             fi
          fi
