A fix.

diff --git a/ci/ci-setup b/ci/ci-setup
--- a/ci/ci-setup
+++ b/ci/ci-setup
@@ -110,11 +110,32 @@ EOF
 
    # ====== Fedora ==========================================================
    elif [ -e /usr/bin/dnf ] ; then
-      PACKAGES="python3 redhat-lsb-core"
+      PACKAGES="clang make python3 redhat-lsb-core"
+      if [ ${USE_PACKAGING} -eq 1 ] ; then
+         # Need to install mock as well:
+         PACKAGES="${PACKAGES} fedora-release findutils mock rpmdevtools"
+      fi
 
       # dnf upgrade -qy
-      dnf install -qy make clang \
-         ${PACKAGES}
+      dnf install -qy ${PACKAGES}
+
+      if [ ${USE_PACKAGING} -eq 1 ] ; then
+         # ====== mock environment ==========================================
+         groupadd -f mock
+
+         release=`cat /etc/fedora-release | sed -e "s/^\(.*\) release \([0-9]*\) (\(.*\))$/\2/g"" | sed -e  "s/[^0-9]//g"`
+         arch=`uname -m | sed -e "s/[^0-9a-zA-Z_+-]//g"`
+         if ! grep "^\[copr-dreibh-ppa\]" /etc/mock/fedora-${release}-${arch}.cfg ; then
+            shopt -s extglob
+            ppa="config_opts['dnf.conf'] += \"\"\"\n[copr-dreibh-ppa]\nname=Copr repo for ppa owned by dreibh\nbaseurl=https://copr-be.cloud.fedoraproject.org/results/dreibh/ppa/fedora-\$releasever-\$basearch/\ntype=rpm-md\nskip_if_unavailable=True\ngpgcheck=1\ngpgkey=https://copr-be.cloud.fedoraproject.org/results/dreibh/ppa/pubkey.gpg\nrepo_gpgcheck=0\nenabled=1\n\"\"\""
+            ppa="${ppa//+( )$/\\n}"
+            echo -e "${ppa}" | tee -a /etc/mock/fedora-${release}-${arch}.cfg
+            if ! grep "^\[copr-dreibh-ppa\]" /etc/mock/fedora-${release}-${arch}.cfg ; then
+               echo >&2 "ERROR: Unable to inject PPA configuration into Mock configuration file /etc/mock/fedora-${release}-${arch}.cfg!"
+               exit 1
+            fi
+         fi
+      fi
 
 
    # ====== Unknown =========================================================
