Improved build scripts.

diff --git a/ci/install b/ci/install
--- a/ci/install
+++ b/ci/install
@@ -19,43 +19,44 @@
 # Contact: dreibh@iem.uni-due.de
 
 
+CONTAINER="ubuntu-test"
 UBUNTU_MIRROR="se.archive.ubuntu.com"
 
 
 # ###### Linux ##############################################################
-if [ "$TRAVIS_OS_NAME" == "linux" ] ; then
+if [ "${TRAVIS_OS_NAME}" == "linux" ] ; then
    # ====== Ubuntu Linux ====================================================
-   if [ "$VARIANT" == "ubuntu" -o "$VARIANT" == "debian" ] ; then
+   if [ "${VARIANT}" == "ubuntu" -o "${VARIANT}" == "debian" ] ; then
       echo "Installing eatmydata ..."
-      sudo docker exec ubuntu-test bash -c "sed -e 's#http://archive.ubuntu.com/ubuntu/#http://${UBUNTU_MIRROR}/ubuntu/#g' -i /etc/apt/sources.list"
-      sudo docker exec ubuntu-test bash -c "apt-get update"
-      sudo docker exec ubuntu-test bash -c "apt-get install -y eatmydata python3"
+      sudo docker exec ${CONTAINER} env LANG=C.UTF-8 sed -e "s#http://archive.ubuntu.com/ubuntu/#http://${UBUNTU_MIRROR}/ubuntu/#g" -i /etc/apt/sources.list
+      sudo docker exec ${CONTAINER} env LANG=C.UTF-8 apt-get update
+      sudo docker exec ${CONTAINER} env LANG=C.UTF-8 apt-get install -y eatmydata python3
 
       # ====== Ubuntu/Debian: extract dependencies ==========================
       echo "Extracting dependencies ..."
-      UBUNTU_DEPS=`sudo docker exec ubuntu-test bash -c "ci/get-dependencies $VARIANT"`
+      UBUNTU_DEPS=`sudo docker exec ${CONTAINER} env LANG=C.UTF-8 ci/get-dependencies ${VARIANT}`
       echo "#### Required packages for build: #####"
-      echo "${UBUNTU_DEPS}"
+      echo "D=${UBUNTU_DEPS}"
 
       # ====== Ubuntu/Debian: set up compiler ===============================
-      if [ "$TOOL" == "compile" ] ; then
+      if [ "${TOOL}" == "compile" ] ; then
          echo "Installing compiler and dependencies ..."
-         sudo docker exec ubuntu-test bash -c "eatmydata apt-get install -y joe clang ${UBUNTU_DEPS}"
+         sudo docker exec ${CONTAINER} env LANG=C.UTF-8 eatmydata apt-get install -y joe clang ${UBUNTU_DEPS}
 
       # ====== Ubuntu/Debian: set up pbuilder ===============================
-      elif [ "$TOOL" == "pbuilder" ] ; then
+      elif [ "${TOOL}" == "pbuilder" ] ; then
          echo "Installing pbuilder and dependencies ..."
-         sudo docker exec ubuntu-test bash -c "eatmydata apt-get install -y joe devscripts pbuilder ${UBUNTU_DEPS}"
+         sudo docker exec ${CONTAINER} env LANG=C.UTF-8 eatmydata apt-get install -y joe devscripts pbuilder ${UBUNTU_DEPS}
 
-         distribution=`sudo docker exec ubuntu-test bash -c "lsb_release -cs" | sed -e "s/[^0-9a-zA-Z]//g"`
-         if [ "$VARIANT" == "debian" ] ; then
+         distribution=`sudo docker exec ${CONTAINER} env LANG=C.UTF-8 lsb_release -cs | sed -e "s/[^0-9a-zA-Z]//g"`
+         if [ "${VARIANT}" == "debian" ] ; then
             if [[ "$DOCKER" =~ ^(debian:)(.*)$ ]] ; then
                distribution="${BASH_REMATCH[2]}"
             fi
          fi
          echo "distribution=$distribution"
 
-         if [ "$VARIANT" == "ubuntu" ] ; then
+         if [ "${VARIANT}" == "ubuntu" ] ; then
             mirror="http://${UBUNTU_MIRROR}/ubuntu/"
          else
             mirror="http://deb.debian.org/debian"
@@ -64,7 +65,7 @@ if [ "$TRAVIS_OS_NAME" == "linux" ] ; then
 
          # ====== pbuilder environment ======================================
          echo "Creating pbuilder environment ..."
-         sudo docker exec ubuntu-test bash -c "cat >/etc/pbuilderrc <<OUTER-EOF
+         sudo docker exec ${CONTAINER} bash -c "env LANG=C.UTF-8 cat >/etc/pbuilderrc <<OUTER-EOF
 DISTRIBUTION=$distribution
 COMPONENTS=\"main universe\"
 MIRRORSITE=$mirror
@@ -76,14 +77,14 @@ cores=\\\`getconf _NPROCESSORS_ONLN\\\`
 export CONCURRENCY_LEVEL=\\\${cores}
 export DEB_BUILD_OPTIONS=\"parallel=\\\${cores}\"
 OUTER-EOF"
-         sudo docker exec ubuntu-test bash -c "cat /etc/pbuilderrc"
-         sudo docker exec ubuntu-test bash -c "eatmydata pbuilder create --debootstrapopts --variant=buildd"
-         sudo docker exec ubuntu-test bash -c "ls -l /var/cache/pbuilder/base.tgz"
+         sudo docker exec ${CONTAINER} env LANG=C.UTF-8 cat /etc/pbuilderrc
+         sudo docker exec ${CONTAINER} env LANG=C.UTF-8 eatmydata pbuilder create --debootstrapopts --variant=buildd
+         sudo docker exec ${CONTAINER} env LANG=C.UTF-8 ls -l /var/cache/pbuilder/base.tgz
 
          # ====== Add ppa:dreibh/ppa, updates and backports =================
-         if [ "$VARIANT" == "ubuntu" ] ; then
+         if [ "${VARIANT}" == "ubuntu" ] ; then
             echo "Ubuntu: adding adding ppa:dreibh/ppa and ${distribution}-backports ..."
-            sudo docker exec ubuntu-test bash -c "eatmydata pbuilder login --save-after-login <<EOF
+            sudo docker exec ${CONTAINER} bash -c "env LANG=C.UTF-8 eatmydata pbuilder login --save-after-login <<EOF
 apt-get install -y software-properties-common
 apt-add-repository -y ppa:dreibh/ppa
 apt-get update
@@ -93,10 +94,10 @@ cat /etc/apt/sources.list.d/*
 echo \"---\"
 EOF"
             wait
-            sudo docker exec ubuntu-test bash -c "ls -l /var/cache/pbuilder/base.tgz"
+            sudo docker exec ${CONTAINER} env LANG=C.UTF-8 ls -l /var/cache/pbuilder/base.tgz
 
             # NOTE: backports may be unavailable -> ignore error on apt-get update!
-            sudo docker exec ubuntu-test bash -c "eatmydata pbuilder login --save-after-login <<EOF
+            sudo docker exec ${CONTAINER} bash -c "env LANG=C.UTF-8 eatmydata pbuilder login --save-after-login <<EOF
 apt-add-repository \"deb http://archive.ubuntu.com/ubuntu/ ${distribution}-updates main universe\"
 apt-add-repository \"deb http://archive.ubuntu.com/ubuntu/ ${distribution}-backports main universe\"
 apt-get update || true
@@ -105,13 +106,14 @@ cat /etc/apt/sources.list
 cat /etc/apt/sources.list.d/*
 echo \"---\"
 apt-get dist-upgrade -y
+echo \"Ready!\"
 EOF"
             wait
-            sudo docker exec ubuntu-test bash -c "ls -l /var/cache/pbuilder/base.tgz"
+            sudo docker exec ${CONTAINER} env LANG=C.UTF-8 ls -l /var/cache/pbuilder/base.tgz
 
-         elif [ "$VARIANT" == "debian" ] ; then
+         elif [ "${VARIANT}" == "debian" ] ; then
             echo "Debian adding ${distribution}-backports ..."
-            sudo docker exec ubuntu-test bash -c "eatmydata pbuilder login --save-after-login <<EOF
+            sudo docker exec ${CONTAINER} bash -c "env LANG=C.UTF-8 eatmydata pbuilder login --save-after-login <<EOF
 apt-get install -y software-properties-common
 apt-add-repository \"deb http://deb.debian.org/debian ${distribution}-updates main universe\"
 apt-add-repository \"deb http://deb.debian.org/debian ${distribution}-backports main universe\"
@@ -120,12 +122,13 @@ echo \"Package repositories:\"
 cat /etc/apt/sources.list
 echo \"---\"
 apt-get dist-upgrade -y
+echo \"Ready!\"
 EOF"
             wait
          fi
 
          echo "##### Checking ... #####"
-         sudo docker exec ubuntu-test bash -c "pbuilder login --save-after-login <<EOF
+         sudo docker exec ${CONTAINER} bash -c "env LANG=C.UTF-8 pbuilder login --save-after-login <<EOF
 echo \"Package repositories:\"
 cat /etc/apt/sources.list
 cat /etc/apt/sources.list.d/*
@@ -135,40 +138,42 @@ EOF"
 
 
       else
-         echo >&2 "ERROR: Invalid setting of TOOL=$TOOL"
+         echo >&2 "ERROR: Invalid setting of TOOL=${TOOL}"
          exit 1
       fi
 
 
    # ======Fedora Core Linux ================================================
-   elif [ "$VARIANT" == "fedora" ] ; then
-      FEDORA_DEPS="`ci/get-dependencies $VARIANT`"
+   elif [ "${VARIANT}" == "fedora" ] ; then
+      FEDORA_DEPS="`ci/get-dependencies ${VARIANT}`"
 
       # ====== Fedora: set up compiler ======================================
-      if [ "$TOOL" == "compile" ] ; then
-         sudo docker exec ubuntu-test bash -c "dnf install -y make clang ${FEDORA_DEPS}"
+      if [ "${TOOL}" == "compile" ] ; then
+         sudo docker exec ${CONTAINER} bash -c "env LANG=C.UTF-8 dnf install -y make clang ${FEDORA_DEPS}"
 
       # ====== Fedora: set up pbuilder ======================================
-      elif [ "$TOOL" == "mock" ] ; then
-         sudo docker exec ubuntu-test bash -c "dnf install -y make findutils rpmdevtools fedora-release mock ${FEDORA_DEPS}"
+      elif [ "${TOOL}" == "mock" ] ; then
+         sudo docker exec ${CONTAINER} bash -c "env LANG=C.UTF-8 dnf install -y make findutils rpmdevtools fedora-release mock ${FEDORA_DEPS}"
 
       else
-         echo >&2 "ERROR: Invalid setting of TOOL=$TOOL"
+         echo >&2 "ERROR: Invalid setting of TOOL=${TOOL}"
          exit 1
       fi
 
    # ======Fedora Core Linux ================================================
    else
-      echo >&2 "ERROR: Invalid setting of VARIANT=$VARIANT"
+      echo >&2 "ERROR: Invalid setting of VARIANT=${VARIANT}"
       exit 1
    fi
 
+
 # ###### Other ##############################################################
-elif [ "$TRAVIS_OS_NAME" == "osx" ] ; then
+elif [ "${TRAVIS_OS_NAME}" == "osx" ] ; then
    echo "TBD"
+
 
 # ###### Error ##############################################################
 else
-   echo >&2 "ERROR: Invalid setting of TRAVIS_OS_NAME=$TRAVIS_OS_NAME"
+   echo >&2 "ERROR: Invalid setting of TRAVIS_OS_NAME=${TRAVIS_OS_NAME}"
    exit 1
 fi
