Another try.

diff --git a/ci/install b/ci/install
--- a/ci/install
+++ b/ci/install
@@ -186,6 +186,22 @@ if [ "${TRAVIS_OS_NAME}" == "linux" ] ; then
    else
       sudo apt-get update
       sudo ci/get-dependencies ubuntu --install
+
+      # ====== Coverity Scan ================================================
+      if [ "${TOOL}" == "coverity" ] ; then
+         mkdir coverity
+         cd coverity
+         wget https://scan.coverity.com/download/linux64 --post-data "token=${COVERITY_TOKEN}&project=${COVERITY_PROJECT}" -O coverity_tool.tar.gz
+         if [ $? -ne 0 ]; then
+            echo 2>&1 "ERROR: Download of Coverity Scan analysis tool failed!"
+            exit 1
+         fi
+         tar xzf coverity_tool.tar.gz
+         rm -f coverity_tool.tar.gz
+         export PATH="coverity/$(ls -d cov*)/bin:$PATH"
+         cd ..
+      fi
+
    fi
 
 
