Another fix.

diff --git a/ci/install b/ci/install
--- a/ci/install
+++ b/ci/install
@@ -33,7 +33,7 @@ if [ "$TRAVIS_OS_NAME" == "linux" ] ; then
       sudo docker exec -t ubuntu-test bash -c "update-locale LANG=C.UTF-8 LC_ALL=C.UTF-8"
 
       # ====== Ubuntu/Debian: set up compiler ===============================
-      if [ "$TOOL" == "compiler" ] ; then
+      if [ "$TOOL" == "compile" ] ; then
          sudo docker exec -t ubuntu-test bash -c "eatmydata apt-get install -y ${UBUNTU_DEPS}"
 
       # ====== Ubuntu/Debian: set up pbuilder ===============================
@@ -77,7 +77,7 @@ EOF
 "
          fi
 
-      elif [ "$TOOL" != "compile" ] ; then
+      else
          echo >&2 "ERROR: Invalid setting of TOOL=$TOOL"
          exit 1
       fi
@@ -85,12 +85,16 @@ EOF
    # ======Fedora Core Linux ================================================
    elif [ "$VARIANT" == "fedora" ] ; then
       # ====== Fedora: set up compiler ======================================
-      if [ "$TOOL" == "compiler" ] ; then
+      if [ "$TOOL" == "compile" ] ; then
          sudo docker exec -t ubuntu-test bash -c "dnf install -y ${FEDORA_DEPS}"
 
       # ====== Fedora: set up pbuilder ======================================
       elif [ "$TOOL" == "mock" ] ; then
          sudo docker exec -t ubuntu-test bash -c "dnf install -y findutils rpmdevtools fedora-release mock ${FEDORA_DEPS}"
+
+      else
+         echo >&2 "ERROR: Invalid setting of TOOL=$TOOL"
+         exit 1
       fi
 
    # ======Fedora Core Linux ================================================
