Started to add FreeBSD support to CI scripts.

diff --git a/ci/install b/ci/install
--- a/ci/install
+++ b/ci/install
@@ -250,6 +250,85 @@ EOF\""
    fi
 
 
+# ###### FreeBSD ############################################################
+elif [ "${TRAVIS_OS_NAME}" == "freebsd" ] ; then
+
+   if [ "${VARIANT}" != "" ] ; then
+#       env LANG=C.UTF-8 ci/retry -t ${RETRY_MAXTRIALS} -p ${RETRY_PAUSE} -- sudo apt-get install -y build-essential fuse libfuse-dev autoconf automake libtool git libbsd-dev e2fslibs-dev
+
+
+      # ====== Build fuse-ufs2 ==============================================
+#       cd qemu-freebsd/fuse-ufs2/
+#       ./autogen.sh
+#       ./configure
+#       cores=`getconf _NPROCESSORS_ONLN 2>/dev/null || echo "1"`
+#       make -j${cores}
+#       cd ../..
+
+
+      # ====== Modify FreeBSD image =========================================
+      # ~~~~~~ Mount ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+      cd qemu-freebsd/
+      imageName="FreeBSD-${VARIANT}-amd64.raw"
+      ls -l ${imageName}
+      mountPoint=`pwd`/mnt
+
+      sudo umount ${mountPoint} 2>/dev/null || true
+      LOOPDEVS=`sudo losetup -j ${imageName} | awk '{ print $1 }' | sed -e "s/:$//g"`
+      for loopdev in ${LOOPDEVS} ; do
+         sudo losetup -d ${loopdev} || true
+      done
+
+      sudo losetup -P -f ${imageName}
+      sudo losetup -j ${imageName}
+      LOOPDEV=`sudo losetup -j ${imageName} | awk '{ print $1 }' | sed -e "s/:$//g"`
+
+      echo "sudo fuse-ufs2/fuse-ufs/fuse-ufs ${LOOPDEV}p3 ${mountPoint} -o rw"
+      sudo fuse-ufs2/fuse-ufs/fuse-ufs ${LOOPDEV}p3 ${mountPoint} -o rw
+
+      # ~~~~~~ Modify ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+      sudo cp ${mountPoint}/etc/rc.conf .
+      sudo bash -c "( echo \"sshd_enable=\\\"YES\\\"\" ; echo \"ifconfig_em0=\\\"DHCP\\\"\" ) >>${mountPoint}/etc/rc.conf"
+      sudo cat ${mountPoint}/etc/rc.conf
+
+      sudo bash -c "echo \"PermitRootLogin prohibit-password\" >>${mountPoint}/etc/ssh/sshd_config"
+      # sudo tail -n 6 ${mountPoint}/etc/ssh/sshd_config
+
+      sudo mkdir -p ${mountPoint}/root/.ssh
+      sudo chmod 700 ${mountPoint}/root/.ssh
+      sudo cp ~/.ssh/id_rsa.pub ${mountPoint}/root/.ssh/authorized_keys
+      sudo chmod 600 ${mountPoint}/root/.ssh/authorized_keys
+
+      # ~~~~~~ Unmount ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+      sudo umount ${mountPoint}
+      sudo losetup -d ${LOOPDEV}
+
+
+      # ====== Start VM =====================================================
+      ssh-keygen -R "[localhost]:7722"
+      qemu-system-x86_64 -m 4096 -hda ${imageName} -netdev user,id=mynet0,hostfwd=tcp:127.0.0.1:7722-:22 -device e1000,netdev=mynet0 &
+
+      ready=0
+      i=0 ; while [ $i -lt 10 ] ; do
+         echo "Waiting for VM to boot ..."
+         sleep 30
+         if ssh -p 7722 -oStrictHostKeyChecking=no -i ~/.ssh/id_rsa root@localhost hostname ; then
+            ready=1
+            break
+         fi
+         echo "not yet booted."
+         let i=$i+1
+      done
+
+      if [ $ready -eq 0 ] ; then
+         echo >&2 "VM did not boot properly!"
+         exit 1
+      fi
+
+      echo "VM is ready!"
+   fi
+
+
 # ###### Other ##############################################################
 elif [ "${TRAVIS_OS_NAME}" == "osx" ] ; then
 
