Some more updates.

diff --git a/ci/install b/ci/install
--- a/ci/install
+++ b/ci/install
@@ -33,26 +33,54 @@ if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
       # NOTE: locales is needed, to get UTF-8 support right!
       sudo docker exec -t ubuntu-test bash -c "apt-get install -y locales eatmydata"
       sudo docker exec -t ubuntu-test bash -c "eatmydata apt-get install -y ${UBUNTU_DEPS}"
-      sudo docker exec -t ubuntu-test bash -c "locale-gen en_US.UTF-8"
-      sudo docker exec -t ubuntu-test bash -c "update-locale LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 LC_ALL=en_US.UTF-8"
+#       sudo docker exec -t ubuntu-test bash -c "locale-gen en_US.UTF-8"
+      sudo docker exec -t ubuntu-test bash -c "update-locale LANG=C.UTF-8 LC_ALL=C.UTF-8"
+
+         # ====== Ubuntu/Debian: set up pbuilder ============================
       if [ "$TOOL" = "pbuilder" ] ; then
          sudo docker exec -t ubuntu-test bash -c "eatmydata apt-get install -y devscripts debhelper pbuilder"
+
+         if [[ "$DOCKER" =~ ^(debian:)(.*)$ ]] ; then
+            distribution="${BASH_REMATCH[2]}"
+         elif [[ "$DOCKER" =~ ^(ubuntu)(.*)$ ]] ; then
+            distribution="${BASH_REMATCH[2]}"
+         else
+            distribution=`sudo docker exec -t ubuntu-test bash -c "lsb_release -cs"`
+         fi
+         echo "distribution=$distribution"
+
+         if [ "$VARIANT" = "ubuntu" ] ; then
+            mirror="http://us.archive.ubuntu.com/ubuntu/"
+         else
+            mirror="http://deb.debian.org/debian"
+         fi
+         echo "mirror=$mirror"
+
          sudo docker exec -t ubuntu-test bash -c "cat >/etc/pbuilderrc <<EOF
-DISTRIBUTION=$DISTRIB_CODENAME
+DISTRIBUTION=$distribution
 COMPONENTS=\"main universe\"
-MIRRORSITE=http://us.archive.ubuntu.com/ubuntu/
+MIRRORSITE=$mirror
 APTCACHEHARDLINK=no
+EXTRAPACKAGES=eatmydata
+EATMYDATA=yes
 EOF
 "
          sudo docker exec -t ubuntu-test bash -c "cat /etc/pbuilderrc"
-         sudo docker exec -t ubuntu-test bash -c "pbuilder create --debootstrapopts --variant=buildd"
+         sudo docker exec -t ubuntu-test bash -c "eatmydata pbuilder create --debootstrapopts --variant=buildd"
 
-         sudo docker exec -t ubuntu-test bash -c "pbuilder login --save-after-login <<EOF
+         # ====== Ubuntu: add ppa:dreibh/ppa ================================
+         if [ "$VARIANT" = "ubuntu" ] ; then
+            sudo docker exec -t ubuntu-test bash -c "pbuilder login --save-after-login <<EOF
 apt install -y software-properties-common
 apt-add-repository -sy ppa:dreibh/ppa
 apt-get update
 EOF
 "
+         fi
+
+      elif [ "$TOOL" != "compiler" ] ; then
+         echo >&2 "ERROR: Invalid setting of TOOL=$TOOL"
+         exit 1
       fi
 
    # ======Fedora Core Linux ================================================
