Improved scripts.

diff --git a/ci/test b/ci/test
--- a/ci/test
+++ b/ci/test
@@ -21,42 +21,56 @@
 
 # ###### Linux ##############################################################
 if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
-   if [ "$TOOL" = "pbuilder" ] ; then
+
+   # ====== pbuilder environment ============================================
+   if [ "$TOOL" == "pbuilder" ] ; then
       CHANGELOG_HEADER="`head -n1 debian/changelog`"
+      PACKAGE=`echo ${CHANGELOG_HEADER} | sed -e "s/(.*//" -e "s/ //g"`
       PACKAGE_VERSION=`echo ${CHANGELOG_HEADER} | sed -e "s/.*(//" -e "s/).*//" -e "s/ //g" -e "s/ //g" -e "s/^[0-9]://g"`
 
       packages=""
+      if [ $#  -eq 0 ] ; then
+         echo "Looking for ${PACKAGE}*${PACKAGE_VERSION}*.deb in /var/cache/pbuilder/result ..."
+         packages="`sudo docker exec ubuntu-test env LANG=C.UTF-8 find /var/cache/pbuilder/result -name "${PACKAGE}*${PACKAGE_VERSION}*.deb"`"
+      fi
       while [ $# -gt 0 ] ; do
          echo "Looking for $1*${PACKAGE_VERSION}*.deb in /var/cache/pbuilder/result ..."
-         packages="${packages} `find /var/cache/pbuilder/result -name "$1*${PACKAGE_VERSION}*.deb"`"
+         packages="${packages} `sudo docker exec ubuntu-test env LANG=C.UTF-8 find /var/cache/pbuilder/result -name "$1*${PACKAGE_VERSION}*.deb"`"
          shift
       done
-      packages=`echo "${packages}" | xargs -n1 | sort -u`
+      packages=`echo "${packages}" | xargs -n1 | sort -u | xargs`
+      if [ "${packages}" == "" ] ; then
+         echo >&2 "ERROR: No packages have been found!"
+         exit 1
+      fi
 
-      for package in $packages ; do
-         echo "Installing ${package} ..."
-         apt-get install -y --allow-downgrades ${package}
-      done
-
+      echo "Installing ${packages} ..."
+      sudo docker exec ubuntu-test env LANG=C.UTF-8 apt-get install -y --allow-downgrades ${packages}
       echo "Done!"
 
-   elif [ "$TOOL" = "mock" ] ; then
+   # ====== mock environment ================================================
+   elif [ "$TOOL" == "mock" ] ; then
       release=`sudo docker exec -t ubuntu-test bash -c "cat /etc/fedora-release | sed -e \"s/^\(.*\) release \([0-9]*\) (\(.*\))$/\2/g\"" | sed -e "s/[^0-9]//g"`
       arch=`sudo docker exec -t ubuntu-test uname -m | sed -e "s/[^0-9a-zA-Z_-+]//g"`
 
       packages=""
+      if [ $#  -eq 0 ] ; then
+         echo "Looking for ${PACKAGE}*${PACKAGE_VERSION}*.rpm in /var/lib/mock/fedora-${release}-${arch}/result ..."
+         packages="`sudo docker exec ubuntu-test env LANG=C.UTF-8 find /var/lib/mock/fedora-${release}-${arch}/result -name "${PACKAGE}*${PACKAGE_VERSION}*.rpm" | grep -v "\.src\.rpm$"`"
+      fi
       while [ $# -gt 0 ] ; do
          echo "Looking for $1*${PACKAGE_VERSION}*.rpm in /var/lib/mock/fedora-${release}-${arch}/result ..."
-         packages="${packages} `find /var/lib/mock/fedora-${release}-${arch}/result -name "$1*${PACKAGE_VERSION}*.rpm"`"
+         packages="${packages} `sudo docker exec ubuntu-test env LANG=C.UTF-8 find /var/lib/mock/fedora-${release}-${arch}/result -name "$1*${PACKAGE_VERSION}*.rpm" | grep -v "\.src\.rpm$"`"
          shift
       done
-      packages=`echo "${packages}" | xargs -n1 | sort -u`
+      packages=`echo "${packages}" | xargs -n1 | sort -u | xargs`
+      if [ "${packages}" == "" ] ; then
+         echo >&2 "ERROR: No packages have been found!"
+         exit 1
+      fi
 
-      for package in $packages ; do
-         echo "Installing ${package} ..."
-         dnf install -y --allow-downgrade ${package}
-      done
-
+      echo "Installing ${packages} ..."
+      sudo docker exec ubuntu-test env LANG=C.UTF-8 dnf install -y --allowerasing ${packages}
       echo "Done!"
 
    fi
