Improved script.

diff --git a/ci/test b/ci/test
--- a/ci/test
+++ b/ci/test
@@ -55,8 +55,13 @@ if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
 
       release=`sudo docker exec -t ubuntu-test bash -c "LANG=C.UTF-8 ; cat /etc/fedora-release | sed -e \"s/^\(.*\) release \([0-9]*\) (\(.*\))$/\2/g\"" | sed -e "s/[^0-9]//g"`
       arch=`sudo docker exec -t ubuntu-test env LANG=C.UTF-8 uname -m | sed -e "s/[^0-9a-zA-Z_-+]//g"`
-      if [ ! -e /var/lib/mock/fedora-${release}-${arch} ] ; then
-         release="rawhide"
+      if ! sudo docker exec -t ubuntu-test cd /var/lib/mock/fedora-${release}-${arch}/result ; then
+         if sudo docker exec -t ubuntu-test cd /var/lib/mock/fedora-rawhide-${arch}/result ; then
+            release="rawhide"
+         else
+            echo >&2 "ERROR: No results have been found!"
+            exit 1
+         fi
       fi
 
       packages=""
